### ISSUE TITLE
课本？

### ISSUE THREAD

**Issue by Great-designer** [BUAA-SE-Compiling/natrium#1]
助教好！请问编译原理课用的是哪本教材啊？

**Comment by Great-designer** [comment]
助教好！请问编译原理课用的是哪本教材啊？

**Comment by Great-designer** [comment]
助教好！请问编译原理课用的课本教材是哪本书啊？

**Comment by Great-designer** [comment]
助教好！请问编译原理课用的课本教材是哪本书啊？

**Comment by fazdzz** [comment]
[去年编译开课前公开的情报](https://shimo.im/docs/ThjYTRvvJQPGRkgq)中有教材相关的内容，鉴于今年形式改变，我的建议是你直接发邮件问助教或者[老师](shaobing@buaa.edu.cn)

**Comment by Great-designer** [comment]
好的，谢啦~
