### ISSUE TITLE
标准库“putstr”接收的应该是什么参数？

### ISSUE THREAD

**Issue by crclz** [BUAA-SE-Compiling/natrium#3]
从 https://c0.karenia.cc/c0/stdlib.html 看出，它接受int这个参数
![image](https://user-images.githubusercontent.com/54950573/101500874-ffdf1b80-39a9-11eb-9314-85dfced88529.png)

但是从 https://c0.karenia.cc/c0/expr.html 可以看出，它接受字符串字面量参数。
![image](https://user-images.githubusercontent.com/54950573/101501117-4d5b8880-39aa-11eb-8cb4-34e407b6246f.png)

在**输入的源代码**里的是哪种啊？
是这种吗？ `putstr("abcdefg")`

**Comment by 01010101lzy** [comment]
是。
在 `putstr("abcd")` 中，你首先要将 `"abcd"` 存进全局变量，然后把编号放到栈里，最后调用。

**Comment by crclz** [comment]
@01010101lzy 那putchar也应该是`putchar('A')`这样吗？

**Comment by 01010101lzy** [comment]
字符字面量是一个 int，指导书里写了

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: crclz<mailto:notifications@github.com>
发送时间: 2020年12月8日 23:24
收件人: BUAA-SE-Compiling/natrium<mailto:natrium@noreply.github.com>
抄送: Rynco Maekawa<mailto:lynzrand@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [BUAA-SE-Compiling/natrium] 标准库“putstr”接收的应该是什么参数？ (#3)


@01010101lzy<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F01010101lzy&data=04%7C01%7C%7C6dc4f9496cad4e18028d08d89b8d5e07%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637430378749336437%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=U%2BB8FgD9Z1HXHpvtQI92kDyP3n1NdCTTL5S1CsVEsv4%3D&reserved=0> 那putchar也应该是putchar('A')这样吗？

―
